Autosync: Update core config files (latest)

diff --git a/openlane/Makefile b/openlane/Makefile
--- a/openlane/Makefile
+++ b/openlane/Makefile
@@ -1,4 +1,9 @@
-# SPDX-FileCopyrightText: 2020 Efabless Corporation
+# Copyright 2025 UmbraLogic Technologies LLC
+#
+# Adapted from Caravel User Project
+#
+# Copyright 2020-2024 Efabless Corporation
+# SPDX-FileCopyrightText:
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
@@ -13,91 +18,95 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
+MAKEFLAGS += --warn-undefined-variables
+
+# set shell to bash
 SHELL := /bin/bash
-MAKEFLAGS+=--warn-undefined-variables
 
-export OPENLANE_RUN_TAG = $(shell date '+%y_%m_%d_%H_%M')
-OPENLANE_TAG ?= 2024.08.15
-OPENLANE_IMAGE_NAME ?= efabless/openlane:$(OPENLANE_TAG)
-designs=$(shell find * -maxdepth 0 -type d)
-
-ROOTLESS ?= 0
-USER_ARGS = -u $$(id -u $$USER):$$(id -g $$USER)
-ifeq ($(ROOTLESS), 1)
-	USER_ARGS =
+ifeq ($(origin LIBRELANE_RUN_TAG), undefined)
+export LIBRELANE_RUN_TAG := $(shell date '+%y_%m_%d_%H_%M')
+endif
+ifeq ($(origin CF_LIBRELANE_TAG), undefined)
+export CF_LIBRELANE_TAG := CC2509c
 endif
 
-openlane_cmd = \
-	"flow.tcl \
-	-design $$(realpath ./$*) \
-	-save_path $$(realpath ..) \
-	-save \
-	-tag $(OPENLANE_RUN_TAG) \
-	-overwrite \
-	-ignore_mismatches"
-openlane_cmd_interactive = "flow.tcl -it -file $$(realpath ./$*/interactive.tcl)"
+export CARAVEL_ROOT := $(CARAVEL_ROOT)
+export PDK := $(PDK)
+export PDK_ROOT := $(PDK_ROOT)
+
+designs = $(shell cd $(PROJECT_ROOT)/openlane && find * -maxdepth 0 -type d)
+current_design = null
+
+LIBRELANE_USE_NIX ?= 0
+
+librelane_args = \
+	--run-tag $(LIBRELANE_RUN_TAG) \
+	--manual-pdk \
+	--pdk-root $(PDK_ROOT) \
+	--pdk $(PDK)
 
 docker_mounts = \
-	-v $$(realpath $(PWD)/..):$$(realpath $(PWD)/..) \
-	-v $(PDK_ROOT):$(PDK_ROOT) \
-	-v $(CARAVEL_ROOT):$(CARAVEL_ROOT) \
-	-v $(HOME)/.ipm:$(HOME)/.ipm \
-	-v $(OPENLANE_ROOT):/openlane
-
-docker_env = \
-	-e PDK_ROOT=$(PDK_ROOT) \
-	-e PDK=$(PDK) \
-	-e MISMATCHES_OK=1 \
-	-e CARAVEL_ROOT=$(CARAVEL_ROOT) \
-	-e OPENLANE_RUN_TAG=$(OPENLANE_RUN_TAG)
+	-m $(PROJECT_ROOT) \
+	-m $(PDK_ROOT) \
+	-m $(CARAVEL_ROOT) \
+	-m $(HOME)/.ipm
 
 ifneq ($(MCW_ROOT),)
-docker_env += -e MCW_ROOT=$(MCW_ROOT)
-docker_mounts += -v $(MCW_ROOT):$(MCW_ROOT)
+export MCW_ROOT:=$(MCW_ROOT)
+docker_mounts += -m $(MCW_ROOT)
 endif
 
-docker_startup_mode = $(shell test -t 0 && echo "-it" || echo "--rm" )
-docker_run = \
-	docker run $(docker_startup_mode) \
-	$(USER_ARGS) \
-	$(docker_mounts) \
-	$(docker_env) \
+ifeq ($(LIBRELANE_USE_NIX),1)
+librelane_run = nix run github:chipfoundry/openlane-2/$(CF_LIBRELANE_TAG) --
+else
+librelane_docker_args = $(shell test -t 0 || echo "--docker-no-tty")
+librelane_run = $(PROJECT_ROOT)/openlane/.venv/bin/python3 -m librelane $(docker_mounts) $(librelane_docker_args) --dockerized 
+endif
 
 list:
 	@echo $(designs)
 
 .PHONY: $(designs)
-$(designs) : % :
-	mkdir -p ./$*/runs/$(OPENLANE_RUN_TAG)
-	rm -rf ./$*/runs/$*
-	ln -s $$(realpath ./$*/runs/$(OPENLANE_RUN_TAG)) ./$*/runs/$*
-	if [[ -f ./$@/interactive.tcl ]]; then \
-		$(docker_run) \
-			$(OPENLANE_IMAGE_NAME) sh -c $(openlane_cmd_interactive); \
-	else \
-		$(docker_run) \
-			$(OPENLANE_IMAGE_NAME) sh -c $(openlane_cmd); \
+$(designs) : export current_design=$@
+$(designs):
+	@config_dir="$(PROJECT_ROOT)/openlane/$@"; \
+	config=""; \
+	for ext in yaml json tcl; do \
+		if [ -f "$$config_dir/config.$$ext" ]; then \
+			config="$$config_dir/config.$$ext"; break; \
+		fi; \
+	done; \
+	if [ -n "$$config" ]; then \
+		cmd='$(librelane_run) $(librelane_args) --ef-save-views-to $(PROJECT_ROOT) --overwrite "$$config"'; \
+		echo "* Running LibreLane on $@ with $$config"; \
+		echo $$cmd; \
+		eval $$cmd; \
 	fi
-	@mkdir -p ../signoff/$*/
-	@cp ./$*/runs/$*/OPENLANE_VERSION ../signoff/$*/
-	@cp ./$*/runs/$*/PDK_SOURCES ../signoff/$*/
-	@cp ./$*/runs/$*/reports/*.csv ../signoff/$*/
 
-.PHONY: openlane
-openlane: check-openlane-env
-	if [ -d "$(OPENLANE_ROOT)" ]; then\
-		echo "Deleting exisiting $(OPENLANE_ROOT)" && \
-		rm -rf $(OPENLANE_ROOT) && sleep 2; \
-		fi
-	git clone https://github.com/The-OpenROAD-Project/OpenLane -b $(OPENLANE_TAG) --depth=1 $(OPENLANE_ROOT) && \
-		cd $(OPENLANE_ROOT) && \
-		export OPENLANE_IMAGE_NAME=efabless/openlane:$(OPENLANE_TAG) && \
-		export IMAGE_NAME=efabless/openlane:$(OPENLANE_TAG) && \
-		$(MAKE) pull-openlane
+librelane: librelane-venv librelane-docker-image
 
-.PHONY: check-openlane-env
-check-openlane-env:
-ifeq ($(OPENLANE_ROOT),)
-	@echo "Please export OPENLANE_ROOT"
-	@exit 1
-endif
+.PHONY: librelane-docker-image
+librelane-docker-image:
+	@echo "LibreLane will automatically pull the appropriate Docker image as needed."
+
+librelane-venv: $(PROJECT_ROOT)/openlane/.venv/manifest.txt
+$(PROJECT_ROOT)/openlane/.venv/manifest.txt: $(PROJECT_ROOT)/openlane/.version-$(CF_LIBRELANE_TAG)
+	rm -rf $(PROJECT_ROOT)/openlane/.venv
+	python3 -m venv $(PROJECT_ROOT)/openlane/.venv
+	PYTHONPATH= $(PROJECT_ROOT)/openlane/.venv/bin/python3 -m pip install --upgrade pip
+	PYTHONPATH= $(PROJECT_ROOT)/openlane/.venv/bin/python3 -m pip install "https://github.com/chipfoundry/openlane-2/tarball/$(CF_LIBRELANE_TAG)"
+	PYTHONPATH= $(PROJECT_ROOT)/openlane/.venv/bin/python3 -m pip freeze > $@
+	
+$(PROJECT_ROOT)/openlane/.version-$(CF_LIBRELANE_TAG):
+	echo "$(CF_LIBRELANE_TAG)" > $@
+	python3 -c 'import os; [os.remove(f) for f in os.listdir("$(@D)") if f.startswith(".version-") and f != os.path.basename("$@")]'
+
+.PHONY: librelane-nix
+librelane-nix:
+	@if ! command -v nix > /dev/null; then\
+		echo "Nix not found. Please install Nix using the LibreLane documentation:"; \
+		echo "	https://librelane.readthedocs.io/en/latest/getting_started/common/nix_installation/index.html"; \
+	else \
+		echo "Activating LibreLane Nix environment…"; \
+		nix develop github:chipfoundry/openlane-2/$(CF_LIBRELANE_TAG); \
+	fi
